default: &default
  authentication_providers: '["faker", "ios", "android", "web", "postman"]' # must be a valid JSON
  authentication_token_expiration_seconds: '432000' # 5.days
  force_account_activation_to_enable_login: 'true'

  enable_max_login_attempts_block: 'true'
  max_allowed_login_attempts: '10'
  login_block_period: '86400' # 1.day

  # This configure how many simultaneous sessions will be allowed by authentication provider (client)
  # eg: 1 unique session per provider (1 session in Android, 1 session in web...)
  # Set to -1 to allow infinite simultaneous sessions per user'
  max_simultaneous_authorizations_per_provider: '1'

  # Auth HTTP Request related config
  auth_token_http_header: 'X-Token'
  auth_token_provider_http_header: 'X-Provider'
  current_locale_http_header: 'X-Locale'
  #
  auth_token_http_param: 'auth_token'
  auth_token_provider_http_param: 'auth_provider'
  current_locale_http_param: 'locale'

  development_api_host: "http://localhost:8080/api/"
  staging_api_host: "api-staging.myapp.mytld"
  production_api_host: "api.myapp.mytld"

  # front-end site hosts (used to generate mailer links)
  host: "localhost:9090"
  site_host: "localhost:9090"

  admin_email: "admin@myapp.mytld"
  contact_email: "contact@myapp.mytld"

  admin_user_email: "admin_user@myapp.mytld"
  system_user_email: "system_user_%s@myapp.mytld"

  # enable this to overwrite all cache configuration across app
  # reminder: if you need cache for some endpoints, take a loke
  # in application_helpers.rb for methods: `with_cacheable_endpoints` & `respond_with_cacheable`
  # who provides out of box a cached url for resources. ex:
  # /api/v1/users
  # /api/v1/cached/users

  cache_enabled: "false"
  send_email_async: "true"

  session_duration: "2592000"

  # Use this to determine CORS configuration
  access_control_allowed_origins: "*"
  access_control_allowed_request_methods: "*"

  rollbar_access_token: ""

  # enable this to prefix all routes with prefix
  prefix_api_path: "true"
  # prefix add to ALL routes in application
  # eg: /api/users/1
  api_prefix_path: 'api'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  site_host: "staging.myapp.mytld"
  host: "api-staging.myapp.mytld"

production:
  <<: *default
  site_host: "myapp.mytld"
  host: "api.myapp.mytld"
